### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by MiikaProject** [millalin/Kids-Say-the-Darndest-Things#1]
* ladattu 19.8.2019 klo 18.24
* kokeilin windows10, vscodella, sain ongelmitta toimimaan paikallisesti 
*  .vscode gitignoreen
* metodit/luokat hyvin nimettyjä
* koodi muuntenkin laadultaan hyvää ja selkeää
* ehkä voisi kommentoida metodeja enemmän,esim lyhyesti selitää mistä kyse/mitä tekee

* tein käyttötapaukset tässä järjestyksessä paikallisesti:
* rekisteröityminen:  toimi hyvin, hieman redirect "quetes" sivulle hämmensi, olisiko rekisteröitymisenjälkeen redirected esim. login luontevampi, rekisteröitymisen validointi toimi ja vääränläinen input johti hyvään ohjeistukseen
* lapsen lisääminen: ilman ohjeistusta syntymäpäivän lisäämine yyyy-mm-dd muodossa hieman vaikea, validointi toimija ohjeisti hyvin. Redirect lapsen lisäämisen jälkeen luontevaan paikkaan, hyvä
* lapsen listaus: toimi ongelmitta, valikko selkeä, hyvä.
* lisää sanonta: ajauduin ongelmaan, minun pitää valita kategoria, mutta ei ole keinoa  valita kategoriaa
* ymmärsin käyttötapausten perusteella, että minulla pitää olla admin käyttäjä että voin tehdäne, tein admin käyttäjän.
* kategorian lisäys ongelmitta admininina
* tämän jälkeen sanonnan lisäyskin onnistui userina

* lapsen tietojen muokkauksessa sain aikaan 404 not found ensimmäisellä kerralla. Kokeilin uudestaan ja toimi oikein. Tuo 404 not found johtui siitä, että ensimmäisellä kerralla syötin syntymäpäiväkenttää epävalidia tietoa, tiedoston child.views rivin 53 perusteella tuo epävalidi päivämäärä johti modifyChild.html sivulle ohjaamiseen ja sen mukana form. Tuossa ei välitetä tietoa child.id tuohon modify.html sivuun. Modifychild.html  rivillä 4 kuitenkin tarvitaan tuota tietoa child.id, mikä johtaa tuohon 404 not found kun submittaa lomakkeen.
* lisäämällä tuo child.id tuohon child.views rivi 53 (return render_template("child/modifyChild.html", form = form, child_id = child_id)sain korjattua tuon.

* kokeilin samat käyttötapaukset myös herokussa, lisäksi sanontojen listaus ja sanontojen haku toimivat
hyvin.
* ulkoasu siisti, selkeä
* tietokanta hyvin toteutettu, tietokantataulu siisti

**Comment by millalin** [comment]
Kiitos huolellisesta, kattavasta katselmoinnista! Tosiaan sivujen ohjaus uuteen osassa vähän vaiheessa.. syntymäpäiväohjeistus ollut mielessä. Tsekkaan ehdottomasti kuntoon kaiken huomaamaasi ja ehdottamasi! :)
