### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by lauriap** [millalin/Kids-Say-the-Darndest-Things#2]
Ladattu la 31.8.2019 klo 14:37

Käyttötapausten testaus

- rekisteröimätön käyttäjä
	- käyttötapaukset toimivat
	- ei voi rekisteröidä samaa nimimerkkiä useampaan kertaan
	- salasanan tarkistus toimii halutulla tavalla
	- kirjautuminen toimii

- rekisteröitynyt käyttäjä
	- järjestelmään voi luoda lapsen, jonka syntymäpäivä on tulevaisuudessa (onko tarkoituksenmukaista?)
	- muuten lapsen lisäys toimii ok	
	- sanontojen CRUD toimii ok

- admin
	- admin-työkalut onnistuneesti piilotettu tavallisilta käyttäjiltä
	- kategorian poisto jättää kategorian alle merkityt sanonnat järjestelmään - mikä niiden kategoriaksi tulee? Null?
	- sanontojen poistaminen onnistuu helposti
	- itsensä poisto adminina kirjaa ulos sovelluksesta - hyvä ratkaisu

Ulkonäkö, saavutettavuus ja käytettävyys

- AChecker ehdottaa kieliversioiden lisäämistä
- sivuston ulkonäkö ja käytettävyys
	- sivusto on kurssin laajuuteen nähden riittävän tyylitelty
	- yläpalkkia voisi selkeyttää laittamalla samaan "kategoriaan" (esim. Lisää lapsi, lapsiesi tiedot jne.) saman vetolaatikon alle, josta sitten kaikki löytyy
	- typo samannimisen lapsen luonnin virheviestissä: "Sinulla on jo tämänniminen lapsi on olemassa."
	- sanonnan lisääminen lapselle oli hieman epäintuitiivista - muut toiminnot ovat yläpalkissa, mutta sanonnan lisääminen ei. Vaihtoehtoinen tapa olisi ollut lomakkeessa määrittää ensin lapsi, jolle sanonta lisätään ja sen jälkeen itse sanonta
	- Sanonnan ja Lapsen lisätiedoissa koko DATETIMEn näyttäminen käyttäjälle ehkä vähän yliampuvaa? Päivämäärä riittäisi.
	- Haku-toiminnossa molempien hakutyyppien näkyminen ruudulla samaan aikaan antoi aluksi ymmärtää, että hakuun voisi laittaa myös päällekkäisiä kriteerejä, ts. hakea sekä kategoriaa että ikää.

Ohjelmakoodi

- järkevä luokittelu kansioihin / osa-alueisiin
- koodi on siistiä, kommentoinnilla kerrottu tärkeimpien metodien tarkoitus
- myös html-puolella jälki on siistiä
- child/forms.py: birthday DateFieldille ei ole määritelty suomenkielistä virheviestiä - palauttaa englanninkielisen standardiviestin
- luokkien ja metodien nimet ovat intuitiivisesti nimettyjä

Yleispalaute:

Projekti täyttää mielestäni kaikki kurssille asetetut vaatimukset - todella hyvää työtä! Myös tykkäyssydämien muotoilu on oikein hyvä :) (viite: keskustelu fuksisaunaillassa)! Pienten kirjoitusvirhekorjausten jälkeen tämä on palautusta vaille valmis. Hienoa ja onnea!!!

**Comment by millalin** [comment]
Kiitos kattavasta katselmoinnista! Yläpalkkiin tosiaan tehty muutaman kerrankin muutoksia järkevöittämiseksi. Sanonnan lisääminen omanaan mietinnän arvoinen ehdotus, toisaalta haluttu listauksesta päästä lisäämään suoraan uusi sanonta ko lapselle.

Adminin poistaessa kategorian tosiaan sanonoille, joissa vain tämä kategoria ei jää liitostaulua, jossa kategoriaa. Toisaalta ei käyttäjän sanontoja voi poistaa tai lisätä muuta kategoriaa. Näiden sanontojen tarkemmissa tiedoissa ei tällöin ole kategorilistauksessa mitään. Jos käyttäjä muokkaa sanontaa on kategoria lisättävä. Tarkoitus tosin olisi, ettei admin paljoa käytössäolevia kategorioita yleensä poistelisi. 

Tsekkaan ehdottamasi jutut vielä miettien mahdollisia muutoksia, kiitos.
